clc
%6RSS Stewart platform 
%% input parameters
trans=[0 0 0];
orient=[0 0 0 ];
r_B=11;
r_P=9.4;
servo_arm_l=2.8;
rod_l=21;
alpha_B=13;
alpha_P=13;

  set(gcf, 'color', 'white','units','pixels','position',[0 0 1920 1080]);
  vidObj=VideoWriter('stewartik.mp4');
vidObj.FrameRate = 24;
open(vidObj);
%% ik call
angles= cal_ik_crankstewart(r_B,...
                                   r_P,...
                                   servo_arm_l,...
                                   rod_l,...
                                   alpha_B*pi/180,...
                                   alpha_P*pi/180,...
                                   trans,... 
                                   orient);
% for animation and visualization
% orientation ' roll pitch yaw
% translation x y z
% combined roll pitch
% combined xyz
% combined rollpiutch xyz

%% function rollpitch sweep
  currFrame= getframe(gcf);
          writeVideo(vidObj, currFrame);
for i=0:0.1:2*pi
    orient=[10*pi/180*cos(i) 10*pi/180*sin(i) 0];
    
%     do_the_stewart(handles);
    cal_ik_crankstewart(r_B,...
                                   r_P,...
                                   servo_arm_l,...
                                   rod_l,...
                                   alpha_B*pi/180,...
                                   alpha_P*pi/180,...
                                   trans,... 
                                   orient);
    drawnow
     currFrame= getframe(gcf);
          writeVideo(vidObj, currFrame);
end
for i=2*pi:-0.1:1
    orient=[10*pi/180*cos(i) 10*pi/180*sin(i) 0];
    
%     do_the_stewart(handles);
    cal_ik_crankstewart(r_B,...
                                   r_P,...
                                   servo_arm_l,...
                                   rod_l,...
                                   alpha_B*pi/180,...
                                   alpha_P*pi/180,...
                                   trans,... 
                                   orient);
    drawnow
     currFrame= getframe(gcf);
          writeVideo(vidObj, currFrame);
end
orient=[0 0 0];
%% function trans xyz sweep
for i=0:0.1:2*pi
    trans=[4*sin(i) 0 0];
    
%     do_the_stewart(handles);
    cal_ik_crankstewart(r_B,...
                                   r_P,...
                                   servo_arm_l,...
                                   rod_l,...
                                   alpha_B*pi/180,...
                                   alpha_P*pi/180,...
                                   trans,... 
                                   orient);
    drawnow
     currFrame= getframe(gcf);
          writeVideo(vidObj, currFrame);
end
for i=0:0.1:2*pi
    trans=[0 4*sin(i) 0];
    
%     do_the_stewart(handles);
    cal_ik_crankstewart(r_B,...
                                   r_P,...
                                   servo_arm_l,...
                                   rod_l,...
                                   alpha_B*pi/180,...
                                   alpha_P*pi/180,...
                                   trans,... 
                                   orient);
    drawnow
     currFrame= getframe(gcf);
          writeVideo(vidObj, currFrame);
end
for i=0:0.1:2*pi
    trans=[0 0 2*sin(i)];
    
%     do_the_stewart(handles);
    cal_ik_crankstewart(r_B,...
                                   r_P,...
                                   servo_arm_l,...
                                   rod_l,...
                                   alpha_B*pi/180,...
                                   alpha_P*pi/180,...
                                   trans,... 
                                   orient);
    drawnow
     currFrame= getframe(gcf);
          writeVideo(vidObj, currFrame);
end
orient=[0 0 0];
     close(gcf)
 close(vidObj);